### ISSUE TITLE
Requesting bump to serialport v2.0.6

### ISSUE THREAD

**Issue by neurobe** [fourquet/meteor-package-serialport#6]
some issues with Windows since v2 fixed in 2.0.3 , knockons from this for Linux fixed in v2.0.5
also significant changes to way ports are detected.

Thanks for your efforts.

**Comment by donaldaverill** [comment]
It took a while to get access to all the build machines, but it's now at 2.0.6.

**Comment by neurobe** [comment]
Thanks Donald
I can report works fine on..
   Linux Mint 64 on x64
   Windows10 64 on x64
   Windows10 32 on x64 - version 2.0.2 fails here

Note that in Linux serialport v2.0.6 increases the time to find ports to 12 seconds (!) - some of the recent changes to serialport dealt with edge cases in Linux. 
Windows remains just 1-2 seconds to find ports.
OSX untested.

**Comment by donaldaverill** [comment]
Thanks @neurobe, I'm not sure what to do about 2.0.2 on Windows 32. I don't have a windows machine to test it on at the moment, but I did publish it and did not receive any errors.
