### ISSUE TITLE
correct usage under windows?

### ISSUE THREAD

**Issue by gandapl** [fourquet/meteor-package-serialport#8]
Running it under windows gave me a BSOD.
Does it work under windows? Using Win 10 64bit.
I'm using it as:
`    serialPort = new SerialPort.SerialPort('COM3', {
`

**Comment by xlinbsd** [comment]
Hello, did you try the npm package instead the deprecating atmospherejs way ?
`meteor npm install serialport`

**Comment by gandapl** [comment]
removed the package, added the package again and edited the code:
`    serialPort = new SerialPort.SerialPort('\\\\.\\COM3', {
`

It works now.
